version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    env_file:
      - ./auth/.env
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user
    env_file:
      - ./user/.env
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    container_name: mailer
    env_file:
      - ./mailer/.env
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
  notifier:
    build:
      context: ./notifier
      dockerfile: Dockerfile
    container_name: notifier
    env_file:
      - ./notifier/.env
    ports:
      - "8084:8084"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge