version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

  mailer-service:
    build:
      context: ./mailer-service
      dockerfile: Dockerfile
    container_name: mailer-service
    env_file:
      - ./mailer-service/.env
    ports:
      - "8083:8083"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
  notifier-service:
    build:
      context: ./notifier-service
      dockerfile: Dockerfile
    container_name: notifier-service
    env_file:
      - ./notifier-service/.env
    ports:
      - "8084:8084"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge